In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [9]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
#Creating Arrays 

arr1 = np.array([1,2,3,4,5]) #The array object in NumPy is called ndarray
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
#Numpy array as tuple

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [20]:
#Dimenions

#0-D 
arr0 = np.array(42)
print(arr)

#1-D 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

#2-D
arr2 = np.array([[1,2,3],[4,5,6]])

#3-D
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

#checkdimensions
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)



42
[1 2 3 4 5]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3


In [4]:
#Higher Dimensional Arrays

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
#Indexing

arr = np.array([1,2,3,4])

print(arr[0])
print(arr[0] + arr[2]) #adding

#2-D

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr1[0,1])
print('3rd elemtn 2nd row: ', arr1[1,2] )

#3-D


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

#negative indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

1
4
2nd element on 1st row:  2
3rd elemtn 2nd row:  8
6
Last element from 2nd dim:  10


In [8]:
#slicing

arr = np.array([1,2,3,4,5])

print(arr[1:5]) #the last number is excluded !
print(arr[2:])
print(arr[:2])


#negative slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])


#step

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[::2])


#slicing 2-D Arrays

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:3])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[2 3 4 5]
[3 4 5]
[1 2]
[5 6]
[2 4]
[1 3 5 7]
[7 8]
[3 8]
[[2 3 4]
 [7 8 9]]


In [13]:
#Numpy Data types

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

#i = integer
#b= boolean
#u= unsigned integer
#f= float
#c= complex float
#m= timedelta
#M= datetime
#O= object
#S= string

int32
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3]
int32


In [8]:
#COPY - keeps the original

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#VIEW - changes automatically

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


#Check base ?

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]


In [10]:
#shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [10]:
#Reshape

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr= arr.reshape(4,3)
print(newarr)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr= arr.reshape(2,3,2)
print(newarr)

#one cannot reshape into any shape

arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

#unknown dimension, only 1

arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)


#flattening arrays

arr = np.array([[1,2,3],[4,5,6]])
newarr= arr.reshape(-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]


In [12]:
#iterating

arr = np.array([1,2,3])

for x in arr :
    print(x)

#2-D

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

  #iterating every single number

  for x in arr:
       for y in x:
        print(y)


#3-D , for x, for y, for z ...


#nditer() - crazy arrays

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)



arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)





1
2
3
[1 2 3]
1
2
3
4
5
6
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7


In [14]:
#enumerate

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [28]:
#join - adding arrays along


#concatenate

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


#stack

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


#hstack - along rows

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


#vstacl - along colums

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


#d-stack - along height

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [32]:
#split

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)
print(newarr)

#it will automatically adjust the end

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

#split 2-D arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [38]:
#search

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


#searchsorted

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


#searchsorted from right side

arr = np.array([6,7,8,9])

x = np.searchsorted(arr, 7, side='right')
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)
1
2


In [39]:
#sort

